In [205]:
import numpy as np
import random

In [206]:
grilleEasy = np.array([[0,3,0,8,7,0,5,4,0],[2,7,0,0,0,0,0,0,1],[9,0,8,0,1,0,0,7,0],[0,0,0,4,6,9,1,5,0],[0,0,0,2,0,0,0,9,0],[1,6,9,7,3,0,0,8,4],[0,0,7,0,0,0,4,0,5],[0,0,0,1,5,0,7,0,3],[0,1,0,3,4,0,0,2,8]])
grilleExpert = np.array([[7,0,0,0,8,0,0,0,0],[0,0,5,0,2,0,0,0,9],[0,0,0,0,0,0,3,0,0],[5,0,0,4,0,0,0,0,0],[0,0,2,0,0,0,8,6,0],[1,0,0,0,0,0,0,0,4],[0,2,0,0,0,7,4,0,0],[0,0,0,0,9,0,2,0,0],[4,0,3,0,0,5,0,0,1]])
grilleExpert
grilleHard = np.array([[0,0,0,4,7,0,0,0,0],[5,0,0,0,6,0,7,3,0],[0,0,0,0,0,0,2,1,9],[0,0,0,0,0,5,9,0,0],[0,0,0,0,2,6,0,0,1],[0,0,6,0,9,1,0,7,0],[4,0,7,0,0,0,5,0,8],[0,0,0,0,0,0,0,0,2],[6,8,0,0,0,0,0,0,0]])
grilleHard
grilleExpert2=np.array([[0,0,0,0,4,0,0,2,6],[3,0,9,7,2,0,0,0,0],[0,5,0,0,0,0,4,0,0],[0,0,7,9,1,3,0,0,0],[6,0,3,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,2],[1,0,0,0,0,0,0,8,0],[0,0,0,0,0,8,0,0,9],[0,9,0,0,0,0,7,0,4]])
print(grilleExpert2)


[[0 0 0 0 4 0 0 2 6]
 [3 0 9 7 2 0 0 0 0]
 [0 5 0 0 0 0 4 0 0]
 [0 0 7 9 1 3 0 0 0]
 [6 0 3 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 2]
 [1 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 8 0 0 9]
 [0 9 0 0 0 0 7 0 4]]


In [161]:
def get_line(x,y,array):
    return array[x]
                 
def get_rest_line(x,y,array):
    return np.delete(array[x,:],y)
    
def get_rest_column(x,y,array):
    return np.delete(array[:,y],x)

def get_rest_box(x,y,array):
    endx = 3+int(x/3)*3
    begx = 0+int(x/3)*3
    endy = 3+int(y/3)*3
    begy = 0+int(y/3)*3
    box = np.array([[]])
    for i in range(begx,endx):
        for j in range(begy,endy):
            if (i!=x)|(j!=y):
                box = np.append(box,array[i,j])
                
    return box

def get_absent_numbers(array):
    aNum = np.array([[]])
    for i in range(1,10):
        if not(i in array):
            aNum = np.append(aNum, i)
    while len(aNum)<9:
        aNum = np.append(aNum, 0)
    return aNum
    

In [247]:
def create_possibility_vec(x,y,array):
    tempVec = np.append(get_rest_column(x,y,array),get_rest_line(x,y,array))
    tempVec = np.append(tempVec, get_rest_box(x,y,array),)
    return get_absent_numbers(tempVec)

def check_matrix(grille):
    for i in range(grille.shape[0]):
        for j in range(grille.shape[1]):
            if grille[i,j] !=0:
                possVec = create_possibility_vec(i,j,grille)
                if not(grille[i,j] in possVec):
                    return False
    return True

def get_coor_vec_2_poss(possMat):
    coor_vec_2_poss=np.array([[]])
    for i in range(possMat.shape[0]):
        for j in range(possMat.shape[1]):
            if np.count_nonzero(possMat[i,j,:])==2:
                if coor_vec_2_poss.shape[1] == 0:
                    coor_vec_2_poss= np.array([[i,j]])
                else:
                    coor_vec_2_poss = np.concatenate((coor_vec_2_poss, np.array([[i,j]])), axis = 0)
    return coor_vec_2_poss
"""
def get_coor_vec_low_poss(possMat):
    coor_vec_low_poss=np.array([[]])
    for i in range(possMat.shape[0]):
        for j in range(possMat.shape[1]):
            if np.count_nonzero(possMat[i,j,:])>1 and np.count_nonzero(possMat[i,j,:])<5:
                if coor_vec_low_poss.shape[1] == 0:
                    coor_vec_low_poss= np.array([[i,j]])
                else:
                    coor_vec_low_poss = np.concatenate((coor_vec_low_poss, np.array([[i,j]])), axis = 0)
    return coor_vec_low_poss
"""
def get_coor_vec_low_poss(possMat):
    coor_vec_low_poss=np.array([[]])
    for i in range(possMat.shape[0]):
        for j in range(possMat.shape[1]):
            if np.count_nonzero(possMat[i,j,:])>1 and np.count_nonzero(possMat[i,j,:])<5:
                if coor_vec_low_poss.shape[1] == 0:
                    coor_vec_low_poss= np.array([[i,j,np.count_nonzero(possMat[i,j,:])]])
                else:
                    coor_vec_low_poss = np.concatenate((coor_vec_low_poss, np.array([[i,j,np.count_nonzero(possMat[i,j,:])]])), axis = 0)
    return coor_vec_low_poss

def get_a_number_yolo(grille, coor_vec_2_poss, possMat, elementNumber):
    x = int(coor_vec_2_poss.shape[0]*np.random.rand())
    #print(x)
    vec = coor_vec_2_poss[x,:]
    #print(vec[0])
    #print(vec[1])
    grille[vec[0],vec[1]] = possMat[vec[0],vec[1],random.randint(0, vec[2]-1)]
    possMat[vec[0],vec[1],:] = np.zeros(9)
    return grille, possMat


In [248]:
get_coor_vec_2_poss(possMat)[0]
print(possMat[get_coor_vec_2_poss(possMat)[0][0],get_coor_vec_2_poss(possMat)[0][1],:])
print(np.zeros(9))

[7. 8. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [249]:
""""
def get_absent_numbers(array):
    aNum = np.array([[]])
    for i in range(1,10):
        if not(i in array):
            aNum = np.append(aNum, i)
    for i in range(aNum.shape[0], 9):
        aNum = np.append(aNum, 0)
    return aNum
"""
def create_possibility_matrix(array):
    possMat=np.zeros((9,9,9))
    for i in range(array.shape[0]):
        for j in range(array.shape[1]):
            if array[i,j] == 0:
                possMat[i,j,:] = create_possibility_vec(i,j,array)
    return possMat

def count_numbers(actualBox):
    numberCountBox=[0]*10
    for i in range(actualBox.shape[0]):
        for j in range(actualBox.shape[1]):
            for k in range(int(actualBox.shape[2])):
                numberCountBox[int(actualBox[i,j,k])] += 1
    return numberCountBox

In [250]:
def only_possibility_case(array, possMat, flag):
    for i in range(possMat.shape[0]):
            for j in range(possMat.shape[1]):
                if array[i,j] == 0 and np.count_nonzero(possMat[i,j,:]) == 1:
                    array[i,j] = possMat[i,j,0]
                    flag = 1
    return array, flag

def only_possibility_box(array, possMat, flag):
    for i in range(int(possMat.shape[0]**(1/2))):
            for j in range(int(possMat.shape[0]**(1/2))):
                actualBox = possMat[np.ix_(range(i*3,3+i*3),range(j*3,3+j*3))]
                vec_count_numbers = count_numbers(actualBox)
                if 1 in vec_count_numbers:
                    coorX = np.where(actualBox == vec_count_numbers.index(1))[0][0]
                    coorY = np.where(actualBox == vec_count_numbers.index(1))[1][0]
                    array[i*3 + coorX,j*3 + coorY] = count_numbers(actualBox).index(1)
                    flag = 1
    return array, flag

#def col_row_interaction(possMat):
#    pass

In [251]:

def solve_sudok(grille):
    grilleRemplie = np.copy(grille)
    iterCount = 0
    flag= 1
    while not(np.count_nonzero(grilleRemplie) == 81 or flag == 0):
        iterCount += 1
        #print(iterCount)
        if not(check_matrix(grilleRemplie)):
            return grilleRemplie, possMat, False, iterCount
        
        possMat = create_possibility_matrix(grilleRemplie)
        possMat = col_row_interaction(possMat)
        if iterCount>3:
            flag = 0
        
        grilleRemplie, flag = only_possibility_case(grilleRemplie, possMat, flag)
        grilleRemplie, flag = only_possibility_box(grilleRemplie, possMat, flag)
        
        if flag==0:
            flag2Essai = 0
            grilleRemplieTemp, possMatTemp = get_a_number_yolo(grilleRemplie,get_coor_vec_low_poss(possMat), possMat, flag2Essai)
            grilleRemplieTemp, possMatTemp, flag2, iterCountTemp = solve_sudok(grilleRemplieTemp)
            
            
            if flag2 == True:
                grilleRemplie = grilleRemplieTemp
                possMat = possMatTemp
                iterCount= iterCount+iterCountTemp
            else:
                if flag2Essai == 1:
                    return grilleRemplie, possMat, False
                else:
                    flag2Essai = 1
                    grilleRemplieTemp, possMatTemp = get_a_number_yolo(grilleRemplie,get_coor_vec_2_poss(possMat), possMat, flag2Essai)
                    grilleRemplieTemp, possMatTemp, flag2, _ = solve_sudok(grilleRemplieTemp)
                    grilleRemplie = grilleRemplieTemp
                    possMat = possMatTemp
                    
        
    if np.count_nonzero(grilleRemplie) != 81:
        #print("failure")
        #print(grilleRemplie)
        pass
    else:
        print(grilleRemplie)
        print("en {} essais".format(iterCount))
    return grilleRemplie, possMat, True, iterCount
                
    

In [263]:
grilleRemplie,possMat,test,_= solve_sudok(grilleExpert2)
print(grilleRemplie)

[[8 7 1 3 4 5 9 2 6]
 [3 4 9 7 2 6 8 5 1]
 [2 5 6 8 9 1 4 7 3]
 [4 2 7 9 1 3 5 6 8]
 [6 8 3 2 5 4 1 9 7]
 [9 1 5 6 8 7 3 4 2]
 [1 3 2 4 7 9 6 8 5]
 [7 6 4 5 3 8 2 1 9]
 [5 9 8 1 6 2 7 3 4]]
en 9 essais
[[8 7 1 3 4 5 9 2 6]
 [3 4 9 7 2 6 8 5 1]
 [2 5 6 8 9 1 4 7 3]
 [4 2 7 9 1 3 5 6 8]
 [6 8 3 2 5 4 1 9 7]
 [9 1 5 6 8 7 3 4 2]
 [1 3 2 4 7 9 6 8 5]
 [7 6 4 5 3 8 2 1 9]
 [5 9 8 1 6 2 7 3 4]]
en 14 essais
[[8 7 1 3 4 5 9 2 6]
 [3 4 9 7 2 6 8 5 1]
 [2 5 6 8 9 1 4 7 3]
 [4 2 7 9 1 3 5 6 8]
 [6 8 3 2 5 4 1 9 7]
 [9 1 5 6 8 7 3 4 2]
 [1 3 2 4 7 9 6 8 5]
 [7 6 4 5 3 8 2 1 9]
 [5 9 8 1 6 2 7 3 4]]


In [119]:
grilleExpert2

array([[0, 0, 0, 0, 4, 0, 0, 2, 6],
       [3, 0, 9, 7, 2, 0, 0, 0, 0],
       [0, 5, 0, 0, 0, 0, 4, 0, 0],
       [0, 0, 7, 9, 1, 3, 0, 0, 0],
       [6, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 2],
       [1, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 8, 0, 0, 9],
       [0, 9, 0, 0, 0, 0, 7, 0, 4]])

In [244]:
grilleExpert2[0,0]
possMat = create_possibility_matrix(grilleExpert2)
test=np.append(get_rest_column(0,0,grilleExpert2),get_rest_line(0,0,grilleExpert2))
get_absent_numbers(test)
possMat
test=get_coor_vec_low_poss(possMat)
vec=test[0]
#possMat[vec[0],vec[1],possMat[vec[0],vec[1],int(vec[2]*np.random.rand())]]
possMat[vec[0],vec[1],int(vec[2]*np.random.rand())]

7.0

In [240]:
print(int(vec[2]*np.random.rand()))
print(int(vec[2]*np.random.rand()))
print(int(vec[2]*np.random.rand()))
print(int(vec[2]*np.random.rand()))
print(int(vec[2]*np.random.rand()))
print(int(vec[2]*np.random.rand()))
print(int(vec[2]*np.random.rand()))


1
0
0
0
1
1
0


In [201]:
get_coor_vec_low_poss(possMat)

array([[0, 0, 2],
       [0, 1, 3],
       [0, 2, 2],
       [0, 3, 4],
       [0, 5, 3],
       [1, 1, 4],
       [1, 5, 3],
       [1, 6, 3],
       [1, 7, 2],
       [1, 8, 3],
       [2, 0, 3],
       [2, 2, 4],
       [2, 3, 4],
       [2, 4, 4],
       [2, 5, 3],
       [2, 7, 4],
       [2, 8, 4],
       [3, 0, 4],
       [3, 1, 3],
       [3, 6, 3],
       [3, 7, 3],
       [3, 8, 2],
       [4, 1, 4],
       [4, 3, 4],
       [4, 4, 3],
       [4, 5, 4],
       [4, 6, 4],
       [4, 8, 4],
       [5, 0, 4],
       [5, 1, 3],
       [5, 2, 4],
       [5, 3, 4],
       [5, 4, 4],
       [5, 5, 4],
       [6, 2, 4],
       [6, 6, 4],
       [6, 8, 2],
       [7, 0, 4],
       [7, 2, 4],
       [7, 4, 4],
       [7, 7, 4],
       [8, 0, 3],
       [8, 2, 4],
       [8, 4, 3],
       [8, 5, 4],
       [8, 7, 4]])

In [51]:
possMat = create_possibility_matrix(grilleHard)

def col_row_interaction(possMat): 

    for xbox in range(3):
        for ybox in range(3):
            actualBox = possMat[np.ix_(range(3*xbox,3+3*xbox),range(3*ybox,3+3*ybox))]
            #print(actualBox)
            posNum=np.zeros((9,3,3))

            for i in range(1,10):
                nbPoss = np.where(actualBox == i)[0].shape[0]
                if nbPoss > 1 and nbPoss < 4:
                    for j in range(nbPoss):
                        x = np.where(actualBox == i)[0][j]
                        y = np.where(actualBox == i)[1][j]
                        z = 1
                        pos = np.array([x,y,z])
                        posNum[i-1,j,:] = pos

                for k in range(2):
                    if np.unique(posNum[i-1,range(np.count_nonzero(posNum[i-1,:,2])),k]).shape[0] == 1: #differente fois le meme nombre tous sur la meme ligne
                        if k == 0:
                            element_number = int(3*xbox+posNum[i-1,0,k])
                        else:
                            element_number = int(3*ybox+posNum[i-1,0,k])
                        possMat = update_possMat(possMat, k, xbox, ybox, element_number, i)
                        #print("le chiffre {} elimine le {} ème {}".format(i, posNum[i-1,0,k], direction))
                        #print("dans la boite située en ({},{})".format(xbox,ybox))
                        
    return possMat




#posNum[6,0] = 

#for i in range(1,10):
    

In [52]:
'''enum = 0
for i in possMat[:,3,:]:
    
    print(enum)
    i = np.delete(i,np.where(i == 7)[0])
    for j in range(i.shape[0],9):
        i = np.append(i,0)
    #print(i)
    possMat[enum,3,:] = i
    enum = enum+ 1
print(possMat[:,3,:])'''


def update_possMat(possMat, direction, element_xbox, element_ybox, element_number, number):
    #direction = 0 pour horizontal, 1 pour vertical
    if direction == 1:
        enum = 0
        #print(element_number)
        for i in possMat[:,element_number,:]:
            if not(enum in range(3*element_xbox, 3+3*element_xbox)):
                #print(enum)
                i = np.delete(i,np.where(i == number)[0])
                for j in range(i.shape[0],9):
                    i = np.append(i,0)
                #print(i)
                possMat[enum,element_number,:] = i
            enum = enum+ 1
    else:
        enum = 0
        for i in possMat[element_number,:,:]:
            if not(enum in range(3*element_ybox, 3+3*element_ybox)):
                #print(enum)
                i = np.delete(i,np.where(i == number)[0])
                for j in range(i.shape[0],9):
                    i = np.append(i,0)
                #print(i)
                possMat[element_number,enum,:] = i
            enum = enum+ 1
    return possMat

    
    

In [53]:
possMat=create_possibility_matrix(grilleExpert)
print(possMat[:,3,:])
update_possMat(possMat, 1, 1, 1, 3, 7)
print(possMat[:,3,:])

[[1. 3. 5. 6. 9. 0. 0. 0. 0.]
 [1. 3. 6. 7. 0. 0. 0. 0. 0.]
 [1. 5. 6. 7. 9. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 3. 5. 7. 9. 0. 0. 0. 0.]
 [2. 3. 5. 6. 7. 8. 9. 0. 0.]
 [1. 3. 6. 8. 0. 0. 0. 0. 0.]
 [1. 3. 6. 8. 0. 0. 0. 0. 0.]
 [2. 6. 8. 0. 0. 0. 0. 0. 0.]]
[[1. 3. 5. 6. 9. 0. 0. 0. 0.]
 [1. 3. 6. 0. 0. 0. 0. 0. 0.]
 [1. 5. 6. 9. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 3. 5. 7. 9. 0. 0. 0. 0.]
 [2. 3. 5. 6. 7. 8. 9. 0. 0.]
 [1. 3. 6. 8. 0. 0. 0. 0. 0.]
 [1. 3. 6. 8. 0. 0. 0. 0. 0.]
 [2. 6. 8. 0. 0. 0. 0. 0. 0.]]


In [54]:
check_matrix(grilleEasy)

True

In [55]:
actualBox = possMat[np.ix_(range(3),range(3))]
actualBox

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 3., 4., 6., 9., 0., 0., 0., 0.],
        [1., 4., 6., 9., 0., 0., 0., 0., 0.]],

       [[3., 6., 8., 0., 0., 0., 0., 0., 0.],
        [1., 3., 4., 6., 8., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[2., 6., 8., 9., 0., 0., 0., 0., 0.],
        [1., 4., 6., 8., 9., 0., 0., 0., 0.],
        [1., 4., 6., 8., 9., 0., 0., 0., 0.]]])

In [56]:
actualBox = possMat[np.ix_(range(3),range(3))]

def count_numbers(actualBox):
    numberCountBox=[0]*10
    for i in range(actualBox.shape[0]):
        for j in range(actualBox.shape[1]):
            for k in range(int(actualBox.shape[2])):
                numberCountBox[int(actualBox[i,j,k])] += 1
    return numberCountBox


In [57]:
np.where(actualBox==count_numbers(actualBox).index(1))[1][0]

0

In [58]:
np.where(actualBox == 2)[0][0]

2

In [59]:
possMat.shape[0]**(1/2)

3.0

In [60]:
count_numbers(actualBox).index(1)

2

In [61]:
4 in range(3)

False

In [62]:
np.count_nonzero(grilleExpert)

22

In [63]:
np.count_nonzero(grilleHard)

25

In [64]:
possMat[range(6,9),,:]

SyntaxError: invalid syntax (<ipython-input-64-bb4140eef700>, line 1)

In [65]:
print(possMat[np.ix_(range(6,9),range(3,6))])

[[[1. 3. 6. 8. 0. 0. 0. 0. 0.]
  [1. 3. 6. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[1. 3. 6. 8. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [1. 3. 4. 6. 8. 0. 0. 0. 0.]]

 [[2. 6. 8. 0. 0. 0. 0. 0. 0.]
  [6. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]]]


In [66]:
x=np.array([[]])
x = np.concatenate((x, np.array([[1,2]])), axis = 0)
x = np.concatenate((x, np.array([[1,2]])), axis = 0)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 0 and the array at index 1 has size 2

In [67]:
x

array([], shape=(1, 0), dtype=float64)

In [68]:
np.array([[]]).shape[1]

0

In [69]:
int(2*np.random.rand())

1

In [70]:
coor_vec_2_poss = np.array([1,2])

In [71]:
coor_vec_2_poss[0]

1

In [72]:
test = get_coor_vec_2_poss(possMat)

In [73]:
test

array([[4, 0],
       [7, 0]])

In [74]:
grilleRemplie

array([[7, 0, 4, 0, 8, 0, 5, 0, 2],
       [8, 0, 5, 0, 2, 0, 0, 4, 9],
       [2, 0, 0, 0, 4, 0, 3, 0, 0],
       [5, 0, 0, 4, 7, 0, 1, 0, 0],
       [3, 4, 2, 9, 1, 9, 8, 6, 5],
       [1, 0, 0, 0, 5, 0, 0, 0, 4],
       [9, 2, 1, 8, 3, 7, 4, 5, 6],
       [6, 5, 0, 1, 9, 4, 2, 0, 0],
       [4, 0, 3, 2, 6, 5, 9, 0, 1]])

In [75]:
get_a_number_yolo(grilleRemplie, test, possMat)

TypeError: get_a_number_yolo() missing 1 required positional argument: 'elementNumber'

In [76]:
possMat[2,8,:]

array([2., 5., 6., 7., 8., 0., 0., 0., 0.])

In [77]:
X=np.array([1,2,3])
np.append(X,1)

array([1, 2, 3, 1])

In [78]:
def yolo(X):
    X=np.append(X,1)
    return X

In [79]:
yolo(X)

array([1, 2, 3, 1])

In [80]:
X

array([1, 2, 3])

In [81]:
grilleRemplie

array([[7, 0, 4, 0, 8, 0, 5, 0, 2],
       [8, 0, 5, 0, 2, 0, 0, 4, 9],
       [2, 0, 0, 0, 4, 0, 3, 0, 0],
       [5, 0, 0, 4, 7, 0, 1, 0, 0],
       [3, 4, 2, 9, 1, 9, 8, 6, 5],
       [1, 0, 0, 0, 5, 0, 0, 0, 4],
       [9, 2, 1, 8, 3, 7, 4, 5, 6],
       [6, 5, 0, 1, 9, 4, 2, 0, 0],
       [4, 0, 3, 2, 6, 5, 9, 0, 1]])

In [82]:
grilleExpert

array([[7, 0, 0, 0, 8, 0, 0, 0, 0],
       [0, 0, 5, 0, 2, 0, 0, 0, 9],
       [0, 0, 0, 0, 0, 0, 3, 0, 0],
       [5, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 8, 6, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 4],
       [0, 2, 0, 0, 0, 7, 4, 0, 0],
       [0, 0, 0, 0, 9, 0, 2, 0, 0],
       [4, 0, 3, 0, 0, 5, 0, 0, 1]])

In [83]:
check_matrix(grilleRemplie)

False